from .AgregarMedico import agregarmedico
from .AgregarPaciente import agregar_paciente
from .AsignarTurno import asignarturno
from .AtenderProximo import atender_proximo
from .HistorialxPaciente import historialporpaciente
from .ListarHistorialxPaciente import listar_historial_pacientes
from .ListarMedico import listarmedico
from .ListarPaciente import listarpaciente
from .Turnoxmedico import verturnopormedico
from .VerHistorial import verhistorial
from .VerTurno import verturno